### ISSUE TITLE
Define Stakeholders

### ISSUE THREAD

**Issue by cyrilleulmi** [markuskaufmann/CAS_SA_Transfer#1]
Take the stakeholders defined in the miro board brainstorming and put them into the architecture documentation.

AC
1. All Stakeholders are listed
2. Most imported stakeholders are identified
3. Put Stakeholders on a "Power - Interest grid"

**Comment by markuskaufmann** [comment]
@cyrilleulmi Please review

**Comment by cyrilleulmi** [comment]
Everything looks good, only changed a bit of explanation text
