### ISSUE TITLE
Create initial version of quality tree incl. quality scenarios

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#11]
Both the quality tree and the scenarios should be placed in arc42/10_quality_requirements.adoc
Have a look at the template text on this page, it gives useful instructions on what to place where.

**Comment by markuskaufmann** [comment]
@cyrilleulmi Subject to discuss on 23/12/2022

**Comment by cyrilleulmi** [comment]
Commited everything on #8 because i forgot that we split the tasks. Further Reviews are done directly on #8
