### ISSUE TITLE
Create deployment diagram / view

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#12]

**Comment by cyrilleulmi** [comment]
Does this need an ADR to check if the customer should be able to self host the physio connect system?

**Comment by markuskaufmann** [comment]
Container view -> Replace Ingress with Load Balancer

**Comment by cyrilleulmi** [comment]
@markuskaufmann Please Review

**Comment by markuskaufmann** [comment]
Review done, closing this issue.
