### ISSUE TITLE
ADR: Security

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#16]
Token, Cookie, MFA, ...

**Comment by markuskaufmann** [comment]
@cyrilleulmi Please review. As discussed earlier on - I dropped some ADRs again, as they were part of the system "Benutzerverwaltung".

**Comment by cyrilleulmi** [comment]
Very good analysis & clear decision. Dropped ADRs could be added as appendix later on.
