### ISSUE TITLE
Define architectural tactics

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#23]

**Comment by cyrilleulmi** [comment]
@markuskaufmann Please Review. Probably another chapter we should discuss with our tutor.

**Comment by markuskaufmann** [comment]
@cyrilleulmi You're right, we should absolutely discuss this with our tutor.

**Comment by markuskaufmann** [comment]
Should be ok the way they are documented now. (according to discussion with tutor)
