### ISSUE TITLE
Crosscutting concepts

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#29]

**Comment by markuskaufmann** [comment]
Discuss with tutor regarding the suitable content in that chapter.

**Comment by markuskaufmann** [comment]
Domain model, Hexagonal architecture, (Security)

**Comment by cyrilleulmi** [comment]
@markuskaufmann please Review. I'm not completely content with the hexagonal architecture chapter. I think we should keep it short, but it feels like something is missing.

**Comment by markuskaufmann** [comment]
Review done, closing this issue.
