### ISSUE TITLE
Solution Strategy

### ISSUE THREAD

**Issue by cyrilleulmi** [markuskaufmann/CAS_SA_Transfer#31]
Arc42 Description: "A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture."

We already have all the ADRs, reference them in this chapter and make a short summary.

**Comment by markuskaufmann** [comment]
@cyrilleulmi Please review. I'm not sure about including the tactics as well, I thought some of them might be suitable. Feel free to remove them if you don't think so ;-).

**Comment by cyrilleulmi** [comment]
Looks very good, kept everything as is
