### ISSUE TITLE
Document building block views

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#32]
context, container, component
maybe wait with domain model until we know where it belongs

**Comment by markuskaufmann** [comment]
Business context -> Link to building block view

**Comment by markuskaufmann** [comment]
@cyrilleulmi Initial version should be ready for review.

**Comment by cyrilleulmi** [comment]
Made a few changes. Messed up the merge from fe14559945, added the changes manually afterwards. @markuskaufmann Please check to be sure that everything is ok.

**Comment by markuskaufmann** [comment]
Review of review done, closing this issue.
