### ISSUE TITLE
Create high-level context diagram

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#34]
- Check slides again concerning context diagram
- External systems should be more abstract (less technical)

**Comment by cyrilleulmi** [comment]
Extracted context diagram from System Landscape. If SystemLandscape changes, the diagram has to be extracted agaiin.

@markuskaufmann please review

**Comment by markuskaufmann** [comment]
Review done, closing this issue.
