### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by cyrilleulmi** [markuskaufmann/CAS_SA_Transfer#39]
- Change rehabilitation definition in glossary according to scientific paper delivered by expert - wont do
- Write the Term "Physio Connect" / "Physioconnect" / "Physio-Connect" the same way throughout the document - done
- Change all instances of "einweisen" to "zuweisen" - done
- Gender correctly <- done
etc

**Comment by markuskaufmann** [comment]
Additionally:

- Check and fix all links (they have to work in the generated PDF, for the VS Code Preview it's not that relevant)

UPDATE: DONE

**Comment by markuskaufmann** [comment]
Replace: "on premise" -> "on-premises"
https://brians.wsu.edu/2016/05/30/premise-premises/
http://blog.dieter-rauscher.de/it/?p=1329

UPDATE: DONE

**Comment by markuskaufmann** [comment]
review page orientations (portrait / landscape)

**Comment by cyrilleulmi** [comment]
Rename "Benutzerverwaltung Wrapper" to "Benutzerverwaltungs Wrapper" (s at the end of Benutzerverwaltung)

UPDATE: DONE

**Comment by markuskaufmann** [comment]
Anhang:
- Funktionale Anforderungen
- Check if can be appended to the whole document

UPDATE: DONE

**Comment by markuskaufmann** [comment]
Abbildungsverzeichnis?

UPDATE: DONE

**Comment by markuskaufmann** [comment]
Domain Model - Try to replace "hard" aggregate references with Id references

**Comment by cyrilleulmi** [comment]
Discuss usage of color in the structurizr dsl - ok as is

**Comment by cyrilleulmi** [comment]
Check / extend glossar

**Comment by cyrilleulmi** [comment]
In the domain model, aggregates reference each other multiple times in the documentation: https://contextmapper.org/docs/aggregate/

Maybe the communication via ID (not via object reference) is implied by the "aggregate relationship" (Relations from aggregates to aggregates are visualized with an "aggregate relationships", relations inside the aggregates are shown as "composition relationships").

I think it's ok to keep the model as is and to not rework it with IDs

**Comment by cyrilleulmi** [comment]
(TBD LINK AUF BUCH EVANS) Einfügen oder entfernen

**Comment by cyrilleulmi** [comment]
> review page orientations (portrait / landscape)

Most tables don't look better in landscape. Some even have cell errors because there is less space for the text.

I switched the "Schnittstellen" Tables from the building blocks chapter to landscape, i think we can keep the rest as is.

**Comment by cyrilleulmi** [comment]
todo: add expert meetings to appendix - done

**Comment by cyrilleulmi** [comment]
todo: add link to git repo - done

**Comment by markuskaufmann** [comment]
> (TBD LINK AUF BUCH EVANS) Einfügen oder entfernen

UPDATE: DONE

**Comment by markuskaufmann** [comment]
"Die Zuweisung der Bausteine ist in der Abbildung Referenz Abbildung visualisiert."
-> Fix reference, which figure do you mean?

**Comment by markuskaufmann** [comment]
Details finished, closing this issue.
