### ISSUE TITLE
Define the system vision statement

### ISSUE THREAD

**Issue by cyrilleulmi** [markuskaufmann/CAS_SA_Transfer#4]

**Comment by cyrilleulmi** [comment]
@markuskaufmann Please review

**Comment by markuskaufmann** [comment]
@cyrilleulmi Please have a quick look again (and close the issue if ok). I changed the structure to prosa form, since I think that the template does not really make sense for german. I think what counts is the core message, and that one is alright 👍 .

**Comment by cyrilleulmi** [comment]
prosa licet
