### ISSUE TITLE
Include constraints in documentation

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#7]

**Comment by markuskaufmann** [comment]
@cyrilleulmi Please review

**Comment by markuskaufmann** [comment]
@cyrilleulmi Please review

**Comment by cyrilleulmi** [comment]
We should probably discuss at the next meeting with our tutor if CS-TEC-30 to CS-TEC-51 really are constraints, but looks good for now.
