### ISSUE TITLE
Explain 3 primary quality attributes

### ISSUE THREAD

**Issue by markuskaufmann** [markuskaufmann/CAS_SA_Transfer#8]
- General documentation (how and where can it be in the arc42 template)
- Create subsequent tasks (e.g. for scenarios)

**Comment by markuskaufmann** [comment]
Subsequent task: #11

**Comment by markuskaufmann** [comment]
@cyrilleulmi Please review

**Comment by cyrilleulmi** [comment]
@markuskaufmann plz review & close

**Comment by markuskaufmann** [comment]
@cyrilleulmi Review done, closing this issue.
